apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: sarfin167/nginx-demo:e462c98673a5def5827d12599553801eacaa1487
        ports:
        - containerPort: 80
