apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: sarfin167/nginx-demo:56c75d14a92582ac264ac84688f795db8b57d1c5
        ports:
        - containerPort: 80
