apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.19.1

images:
  # Fix the broken kube-rbac-proxy image
  - name: gcr.io/kubebuilder/kube-rbac-proxy
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: v0.15.0

  # IMPORTANT: Pin the operator image to the correct version
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1

namespace: awx
# force-update
