apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: NodePort
  ingress_type: none
  projects_storage_size: 8Gi
  postgres_image: quay.io/sclorg/postgresql-15-c9s
  postgres_image_version: "15"