apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/syedarfin167/my-k8s-apps.git
    targetRevision: main
    path: awx
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
